#-------MINIMO COMUN MULTIPLO (MCM)--------------
"""ES EL MENOR NUMERO QUE ES MULTIPLO COMUN A DOS O MÁS NUMEROS"""
#EJ.: ENTRE 2, 4 Y 10. EL MCM ES EL  20

#AQUI  SE MULTIPLICAN TODOS LOS NUMEROS CON SU MAYOR EXPONENTE
#EL FAMOSO "CONTADOR" LO USAN PARA SABER CUANTAS REPETICIONES TUVO EL WHILE

#-------MAXIMO COMUN DIVISOR (MCD)--------------
"""ES EL MAYOR NUMERO QUE DIVIDIE EXACTAMENTE A DOS O MAS NUMEROS"""
#EJ.: ENTRE 12 Y 18. EL MCD ES EL 6 

# 2366 -> 2        273 -> 1
# 1183 -> 7        91 -> 3
# 169 -> 13        13 -> 7
# 13 -> 13         13 -> 13
# 1 ->             1 ->  

#SE REPITE 13 Y 7, SU MULTIPLICACION DA 91 QUE ES EL MCD
#LOS NUMEROS QUE SE REPITEN VAN CON SU MENOR EXPONENTE Y SE MULTIPLICAN PARA ENCONTRAR EL MCD